name: Branch protection

on:
  pull_request:
    branches:
      - 'product'

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - name: waiting for success
        run: sleep 20 echo "Always success"

  # hogera:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: exit 1