name: Branch protection

on:
  pull_request:

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Always success"

  hogera:
    runs-on: ubuntu-latest

    steps:
      - run: exit 1