name: merge into main from product

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Branch protection
    types:
      - completed

jobs:
  merge-into-main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # auto created token
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Make fail if the previous workflow was failed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo '::error::Previous workflow was failed'
          exit 1

      - name: check out branch
        uses: actions/checkout@v2
        # productブランチにチェックアウト
        with:
          ref: product

      - name: create pr into main from product
        # ref を判定 ここではawsパイプラインからproductを指定される想定
        id: open-pr-main
        # -B マージする対象ブランチ -t プルリクのタイトル -b プルリクの本文
        # ::set-output name=KEY_NAME::valueでsteps内で使用できる変数にセットする
        # ここでsetされるのは対象のプルリクURL
        # merge時のtargetとして使用する
        # run: |
        #   git branch
        #   echo ${{ github.ref }}
        run: |
          git branch
          echo ${{ github.ref }}
          echo "::set-output name=target-pr-url::$(gh pr create -B main -t 'auto create pr' -b 'merge into main')"

      # test branch
      - name: merge pr into main from product
        # -m 対象のブランチをマージする
        # ここではproductをmainにマージする
        # if: ${{steps.open-pr-main.outputs.target-pr-url != ''}}
        if: ${{steps.outputs.target-pr-url != ''}}
        run: |
          gh pr merge ${{steps.open-pr-main.outputs.target-pr-url}} -m
