name: merge into master from product

on:
  workflow_dispatch:

jobs:
  merge-into-master:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # auto created token
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: check out branch
        uses: actions/checkout@v2
        # productブランチにチェックアウト
        with:
          ref: product

      - name: create pr into master from product
        # ref を判定 ここではawsパイプラインからproductを指定される想定
        if: contains(toJSON(github.ref), 'product')
        id: open-pr-master
        # -B マージする対象ブランチ -t プルリクのタイトル -b プルリクの本文
        # ::set-output name=KEY_NAME::valueでsteps内で使用できる変数にセットする
        # ここでsetされるのは対象のプルリクURL
        # merge時のtargetとして使用する
        run: |
          echo "::set-output name=open-pr-master::$(gh pr create -B master -t 'auto create pr' -b 'merge into master')"

      # test branch
      - name: merge pr into master from product
        if: contains(toJSON(github.ref), 'product')
        # -m 対象のブランチをマージする
        # ここではproductをmasterにマージする
        # run: |
        #   gh pr merge ${{steps.open-pr-test.outputs.open-pr-master}} -m
